#!/usr/bin/bash

build=""

if [ -f /usr/bin/ninja ]; then
     build="-G Ninja"
fi

cmake -B build $build -DCMAKE_BUILD_TYPE=Release || exit
cmake --build build || exit

if [ ! -d ./scripts/imgs ]; then
     mkdir scripts/imgs
fi

rm scripts/imgs/*.svg
scripts/venv/bin/python3 scripts/bench.py
scripts/venv/bin/python3 scripts/gen_pdf.py