#!/usr/bin/bash

export OMP_NUM_THREADS=$(lscpu -p | egrep -v '^#' | sort -u -t, -k 2,4 | wc -l)
export OMP_PROC_BIND=true
export OMP_PLACES=cores

build=""

if [ -f /usr/bin/ninja ]; then
     build="-G Ninja"
fi

a_tol=1e-6
f_point=double

# gcc seq
rm -rf build
cmake -B build $build -DCMAKE_BUILD_TYPE=Release -DA_TOL=$a_tol -DFPOINT_T=$f_point -DOPT=OFF || exit
cmake --build build || exit
maqao OV -R1 -xp=maq_gcc_seq --replace ./build/src/main

# gcc par
rm -rf build
cmake -B build $build -DCMAKE_BUILD_TYPE=Release -DA_TOL=$a_tol -DFPOINT_T=$f_point -DOPT=ON || exit
cmake --build build || exit
maqao OV -R1 -xp=maq_gcc_par --replace ./build/src/main


if [ ! -f /usr/bin/clang ]; then
     exit
fi

export CC=clang
export CXX=clang++

#clang seq
rm -rf build
cmake -B build $build -DCMAKE_BUILD_TYPE=Release -DA_TOL=$a_tol -DFPOINT_T=$f_point -DOPT=OFF || exit
cmake --build build || exit
maqao OV -R1 -xp=maq_clang_seq --replace ./build/src/main

#clang par
rm -rf build
cmake -B build $build -DCMAKE_BUILD_TYPE=Release -DA_TOL=$a_tol -DFPOINT_T=$f_point -DOPT=ON || exit
cmake --build build || exit
maqao OV -R1 -xp=maq_clang_par --replace ./build/src/main


maqao OV -CR -xp=maq_cmp --inputs=maq_gcc_seq,maq_gcc_par,maq_clang_seq,maq_clang_par