#!/usr/bin/bash

export OMP_NUM_THREADS=$(lscpu -p | egrep -v '^#' | sort -u -t, -k 2,4 | wc -l)
export OMP_PROC_BIND=true
export OMP_PLACES=cores

build=""

if [ -f /usr/bin/ninja ]; then
     build="-G Ninja"
fi

cmake -B build $build -DCMAKE_BUILD_TYPE=Release -DA_TOL=1e-10 -DFPOINT_T=double -DOPT=ON || exit
cmake --build build || exit

maqao OV -R1 -xp=ov1 --replace ./build/src/main
# open ov1/RESULTS/main_one_html/index.html 