#!/usr/bin/bash

cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release || exit
cmake --build build || exit

build/src/main exit

cd visu

if [ ! -d ./venv ]; then
     python3 -m venv venv
fi

venv/bin/manim -qm -p anim.py || exit