#!/usr/bin/bash

# export OMP_NUM_THREADS=1
export OMP_NUM_THREADS=$(lscpu -p | egrep -v '^#' | sort -u -t, -k 2,4 | wc -l)
export OMP_PROC_BIND=true
export OMP_PLACES=cores

build=""

if [ -f /usr/bin/ninja ]; then
     build="-G Ninja"
fi

# cmake -B build $build -DCMAKE_BUILD_TYPE=Release || exit
cmake -B build $build -DCMAKE_BUILD_TYPE=Release -DA_TOL=1e-10 -DFPOINT_T=double -DOPT=OFF || exit
cmake --build build || exit

build/src/main exit

cd scripts

if [ ! -d ./venv ]; then
     python3 -m venv venv
     venv/bin/pip install -r ./requirements.txt || exit
fi

./venv/bin/manim -qm -p anim.py || exit