#!/usr/bin/bash

build=""

if [ -f /usr/bin/ninja ]; then
     build="-G Ninja"
fi

# cmake -B build $build -DCMAKE_BUILD_TYPE=Release || exit
cmake -B build $build -DCMAKE_BUILD_TYPE=Debug -DA_TOL=1e-10 -DFPOINT_T=double || exit
cmake --build build || exit

build/src/main exit

cd scripts

if [ ! -d ./venv ]; then
     python3 -m venv venv
     venv/bin/pip install -r ./requirements.txt || exit
fi

./venv/bin/manim -qm -p anim.py || exit